#!/bin/bash
#SBATCH --partition=node6348             # Specfied computation region(PBS -q)
#SBATCH --job-name=scw_Conduct_10       # Name of mission(PBS -N)
#SBATCH --nodes=1                      # Require two nodes
#SBATCH --ntasks-per-node=1           # Each nodes 32 threads is required
#SBATCH --time=156:00:00                # Max running time
#SBATCH --output=out_PT_10.txt         # Standard output diary(PBS -o)
#SBATCH --error=err_PT_10.txt          # Error output diary(PBS -e)

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
#source activate quspin
export PYTHONUNBUFFERED=1
# Switch to the working directory when submitting the job
cd $SLURM_SUBMIT_DIR

# Do MPI with srun
python ConductCalculate10.py

echo 'done'
